# Generated by Django 4.2.6 on 2023-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_feedback_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('expirationDate', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('cardHolderName', models.CharField(max_length=30)),
            ],
        ),
    ]
