# Generated by Django 4.2.6 on 2023-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='expirationDate',
            field=models.DateField(),
        ),
    ]
